#!/usr/bin/env python3
"""Cross-check sesh's pinned BLS vector against an independent implementation.

sesh's `BLS_PINNED_SIG` (src/crypto.rs) was generated by sesh itself, so it is a
regression pin rather than a conformance vector. This script regenerates the same
signature with py_ecc (an independent, pure-Python BLS implementation
maintained by the Ethereum Foundation) and checks that the two agree.

py_ecc's `G2Basic` ciphersuite is exactly the one sesh uses: minimal-pubkey-size
(pubkeys in G1, signatures in G2), basic scheme, DST
`BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_NUL_`.

Run outside the sandbox (it installs a package):

    python3 -m venv /tmp/pyecc && /tmp/pyecc/bin/pip install py_ecc
    /tmp/pyecc/bin/python scripts/verify_bls_vector.py

Exits non-zero on any mismatch. If it passes, `BLS_PINNED_SIG` may be re-labelled
in src/crypto.rs from a regression pin to a cross-implementation vector.
"""

import hashlib
import sys

from py_ecc.bls import G2Basic

# -------------------------------------------------------------------------
# The three values sesh produces. Any mismatch below is a real disagreement
# -------------------------------------------------------------------------
MSG = b"sesh-bls-dst-test-vector"
EXPECTED_DST = b"BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_NUL_"
EXPECTED_SK_BE = "4a342891fd2f79546354aa662d9a544ee9c85628f9b244b13aae5ed942465ac3"
EXPECTED_PK_G1 = (
    "a3ce45ba081e5802bf245c46ad21490e2e8cd66449e09ed8ea39d51f9ff6cb0f"
    "6201b8edd2ec06cd12fd48b5bd0434f0"
)
EXPECTED_SIG = (
    "b218215615e4af6bf4207deb95170edbf9a5284952e9a6f38396af84a262d7d0"
    "197d2560389ad8dbf47a24a338ff17f403caec1eb41f492ade88c6c302010dbf"
    "a4e45d0bd31dd905342abcf38ac9a0fc7e16dd203566f8a72365aa449fd6f245"
)

R = 0x73EDA753299D7D483339D80809A1D80553BDA402FFFE5BFEFFFFFFFF00000001

failures = []


def check(label, got, want):
    ok = got == want
    print(f"{'ok  ' if ok else 'FAIL'}  {label}")
    if not ok:
        print(f"        got  {got}")
        print(f"        want {want}")
        failures.append(label)


def derive_sig_scalar(seed: bytes) -> int:
    """Reimplementation of sesh's hash_to_scalar(DST_SIG_SUBKEY, seed).

    SHA3-256 over the length-prefixed (dst, input, counter) tuple, read
    little-endian, rejecting candidates >= r or == 0.
    """
    dst = b"sesh-sig"
    counter = 0
    while True:
        h = hashlib.sha3_256()
        h.update(len(dst).to_bytes(8, "little"))
        h.update(dst)
        h.update(len(seed).to_bytes(8, "little"))
        h.update(seed)
        h.update(counter.to_bytes(4, "little"))
        cand = int.from_bytes(h.digest(), "little")
        if 0 < cand < R:
            return cand
        counter += 1


# py_ecc names the ciphersuite DST itself; confirm it is the one sesh froze
check("ciphersuite DST matches py_ecc's G2Basic", G2Basic.DST, EXPECTED_DST)

sk = derive_sig_scalar(bytes([42]) * 32)
check("s_sig = derive_sig_scalar(seed(42))", sk.to_bytes(32, "big").hex(), EXPECTED_SK_BE)

pk = G2Basic.SkToPk(sk)
check("pubkey g1 = s_sig * G1", pk.hex(), EXPECTED_PK_G1)

sig = G2Basic.Sign(sk, MSG)
check("signature over the test message", sig.hex(), EXPECTED_SIG)

check("py_ecc verifies its own signature", G2Basic.Verify(pk, MSG, sig), True)
check(
    "py_ecc verifies sesh's pinned signature",
    G2Basic.Verify(pk, MSG, bytes.fromhex(EXPECTED_SIG)),
    True,
)

# Negative control: the pre-fix DST (no SC_TAG) must NOT reproduce the vector.
# If this passes, the pin is not actually sensitive to the DST.
old_dst = b"BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_"
saved, G2Basic.DST = G2Basic.DST, old_dst
try:
    old_sig = G2Basic.Sign(sk, MSG)
finally:
    G2Basic.DST = saved
check("old DST produces a DIFFERENT signature", old_sig.hex() != EXPECTED_SIG, True)

print()
if failures:
    print(f"{len(failures)} MISMATCH(ES): {', '.join(failures)}")
    sys.exit(1)
print("All checks passed: sesh's pinned vector agrees with py_ecc.")
